
program: all.h utilities.c secondrun.c preprocessor.c macros.c labels.c input.c firstrun.c externals.c entries.c encoding.c commands.c cleanup.c assembler.c
	gcc -Wall -g -ansi -pedantic all.h utilities.c secondrun.c preprocessor.c macros.c labels.c input.c firstrun.c externals.c entries.c encoding.c commands.c cleanup.c assembler.c -o compiler
